quarkus:
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      # TODO: point to the docker container from the same compose
      url: jdbc:postgresql://localhost:5435/immich_compactor
    devservices:
      enabled: false
  flyway:
    migrate-at-start: true
  web-bundler:
    dependencies:
      compile-only: false

"%dev": # these configs are for local development (quarkusDev)
  quarkus:
    security:
      auth:
        enabled-in-dev-mode: false
    datasource:
      db-kind: postgresql
      username: postgres
      password: postgres
      jdbc:
        url: jdbc:postgresql://localhost:5435/immich_compactor
    hibernate-orm:
      schema-management:
        strategy: validate
#EOF
