quarkus:
  datasource:
    db-kind: sqlite
    jdbc:
      url: jdbc:sqlite:data/immich_compactor.db
      new-connection-sql: "PRAGMA foreign_keys = ON;"
  flyway:
    migrate-at-start: true
  hibernate-orm:
    database:
      generation: validate
  web-bundler:
    dependencies:
      compile-only: false

"%dev": # these configs are for local development (quarkusDev)
  quarkus:
    security:
      auth:
        enabled-in-dev-mode: false
    datasource:
      jdbc:
        url: jdbc:sqlite:sandbox/immich_compactor.db
        new-connection-sql: "PRAGMA foreign_keys = ON;"
#EOF
