
--
DROP TABLE IF EXISTS immich_server_info;

CREATE TABLE immich_server_info(
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url     text NOT NULL
);

--
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_key     text NOT NULL,
    name        text NOT NULL
);

--
DROP TABLE IF EXISTS staging_area;

CREATE TABLE staging_area (
    user_id     bigint NOT NULL,
    id          text NOT NULL,
    checksum    text NOT NULL,
    next_action text NOT NULL
);

--
DROP TABLE IF EXISTS already_converted;

CREATE TABLE already_converted (
    id          text NOT NULL,
    checksum    text NOT NULL
);

-- EOF
