
--
/* DROP TABLE IF EXISTS configuration;

CREATE TABLE configuration(
    id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
);

INSERT INTO configuration(); */

--
DROP TABLE IF EXISTS user_info;

CREATE TABLE user_info (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_key             text NOT NULL,
    name                text NOT NULL,
    immich_server_url   text NOT NULL
);

--
DROP TABLE IF EXISTS assets_staging_area;

CREATE TABLE assets_staging_area (
    user_id         bigint NOT NULL,
    asset_id        uuid NOT NULL PRIMARY KEY,
    current_state   text NOT NULL,

    CONSTRAINT fk_users
        FOREIGN KEY (user_id)
            REFERENCES user_info(id)
            ON DELETE CASCADE
);

--
DROP TABLE IF EXISTS converted_assets;

CREATE TABLE converted_assets (
    user_id         bigint NOT NULL,
    asset_id        uuid NOT NULL,
    current_state   text NOT NULL,

    CONSTRAINT fk_users
        FOREIGN KEY (user_id)
            REFERENCES user_info(id)
            ON DELETE CASCADE
);

-- EOF
